CREATE TABLE [dbo].[CadCtaPg] (
    [CTREG]     INT           IDENTITY (1, 1) NOT NULL,
    [CTDTREF]   DATETIME      NULL,
    [CTFORNEC]  INT           NULL,
    [CTNF]      INT           NULL,
    [CTDUPL]    NVARCHAR (12) NULL,
    [CTEVENTO]  INT           NULL,
    [CTDTNF]    DATETIME      NULL,
    [CTCCUSTO]  SMALLINT      NULL,
    [CTSETOR]   SMALLINT      NULL,
    [CTSOLIC]   INT           NULL,
    [CTOC]      INT           NULL,
    [CTEMPENHO] INT           NULL,
    [CTSUBEMP]  INT           NULL,
    [CTDTVCTO]  DATETIME      NULL,
    [CTVALOR]   MONEY         NULL,
    [CTVALORDP] MONEY         NULL,
    [CTDTPAGTO] DATETIME      NULL,
    [CTVALORP]  MONEY         NULL,
    [CTDOCPG]   INT           NULL,
    [CTBANCO]   NVARCHAR (4)  NULL,
    [CTAG]      NVARCHAR (20) NULL,
    [CTCONTA]   NVARCHAR (20) NULL,
    [CTSTATUS]  NVARCHAR (5)  NULL,
    [CTHIST]    VARCHAR (500) NULL,
    [CTANOMES]  INT           NULL,
    [CTVALORM]  MONEY         NULL,
    [CTVALORJ]  MONEY         NULL,
    [CTVALORD]  MONEY         NULL,
    [CTHISTPG]  VARCHAR (500) NULL,
    [CTTPCONT]  REAL          NULL,
    CONSTRAINT [PK_CadCtaPg] PRIMARY KEY CLUSTERED ([CTREG] ASC)
);

