CREATE TABLE [dbo].[CADGRUPO] (
    [GRGRUPO] INT           NOT NULL,
    [GRDESC]  NVARCHAR (30) COLLATE Latin1_General_CI_AS NOT NULL,
    [GRDCTO]  NUMERIC (18)  NULL,
    CONSTRAINT [PK_CADGRUPO] PRIMARY KEY CLUSTERED ([GRGRUPO] ASC)
);

