CREATE TABLE [dbo].[CadItemMYSql] (
    [ItId]        INT             IDENTITY (1, 1) NOT NULL,
    [ItSegmento]  INT             NULL,
    [ItGrupo]     INT             NULL,
    [ItSubGrp]    INT             NULL,
    [ItItem]      NCHAR (13)      NULL,
    [ItTipo]      NCHAR (1)       NULL,
    [ItUnid]      NCHAR (10)      NULL,
    [ItDesc]      NVARCHAR (80)   NULL,
    [ItEstqMin]   NUMERIC (10, 2) NULL,
    [ItEstqMax]   NUMERIC (10, 2) NULL,
    [ItCompra]    NUMERIC (10, 2) NULL,
    [ItLucro]     NUMERIC (10, 2) NULL,
    [ItVLucro]    NUMERIC (10, 2) NULL,
    [ItVenda]     NUMERIC (10, 2) NULL,
    [ItDcto]      NUMERIC (10, 2) NULL,
    [ItSaldo]     NUMERIC (10, 2) NULL,
    [ItComissao]  NUMERIC (10, 2) NULL,
    [ItConvenio]  INT             NULL,
    [ItPromo]     BIT             NULL,
    [ItAtivo]     BIT             NULL,
    [ItCNAE]      NCHAR (10)      NULL,
    [ItNCM]       NCHAR (10)      NULL,
    [ItCEST]      NCHAR (10)      NULL,
    [ItCST]       NCHAR (10)      NULL,
    [ItCFOP]      NCHAR (10)      NULL,
    [ItALQICMS]   NUMERIC (10, 2) NULL,
    [ItALQPIS]    NUMERIC (10, 2) NULL,
    [ItALQCOFINS] NUMERIC (10, 2) NULL,
    [ItALQISS]    NUMERIC (10, 2) NULL,
    [ItIMAGEM]    NVARCHAR (MAX)  NULL,
    [ItEAN]       NCHAR (13)      NULL,
    [ItLISTSERV]  NCHAR (5)       NULL,
    [ItANVISA]    NCHAR (13)      NULL,
    CONSTRAINT [PK_CadItemMYSql] PRIMARY KEY CLUSTERED ([ItId] ASC)
);

