CREATE TABLE [dbo].[CADUSER] (
    [USUARIO]  NVARCHAR (20) COLLATE Latin1_General_CI_AS NOT NULL,
    [USSENHA]  NVARCHAR (20) COLLATE Latin1_General_CI_AS NOT NULL,
    [USNOME]   NVARCHAR (80) COLLATE Latin1_General_CI_AS NOT NULL,
    [USAUT]    NVARCHAR (2)  COLLATE Latin1_General_CI_AS NOT NULL,
    [USATIV]   NVARCHAR (1)  COLLATE Latin1_General_CI_AS NOT NULL,
    [USEMAIL]  NVARCHAR (80) COLLATE Latin1_General_CI_AS NULL,
    [USCODFOL] INT           NULL,
    [USCCUSTO] SMALLINT      NULL,
    [USNIVEL]  NVARCHAR (4)  COLLATE Latin1_General_CI_AS NULL,
    [USID]     NCHAR (10)    COLLATE Latin1_General_CI_AS NULL
);

