CREATE VIEW dbo.JSaldoEstq
AS
SELECT     dbo.CADESTOQUE.ETITEM, dbo.CadItem.MSDESC, SUM(dbo.CADESTOQUE.ETQTDE - dbo.CADESTOQUE.ETQTDS) AS SALDO
FROM         dbo.CADESTOQUE INNER JOIN
                      dbo.CadItem ON dbo.CADESTOQUE.ETITEM COLLATE Latin1_General_CI_AI = dbo.CadItem.MSMAT
GROUP BY dbo.CADESTOQUE.ETITEM, dbo.CadItem.MSDESC